apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat0-deployment
  labels:
    app: tomcat0-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat0
  template:
    metadata:
      labels:
        app: tomcat0
    spec:
      containers:
      - name: tomcat
        image: myACR0621.azurecr.io/tomcat:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-front
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: tomcat0
